name: chuck_norris_jokes
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management, Injection Dependecy and Route Management
  get: ^4.6.5

  # Compare objects
  equatable: ^2.0.5

  # Check the Internet connection
  internet_connection_checker: ^1.0.0+1

  # For HTTP requests
  http: ^0.13.5

  # Persistent storate for simple data
  shared_preferences: ^2.0.18

  # Function Programming
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Unity Tests
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
